//! Maintainer-only offline cross-check hook for tools/calibrate-policy.py.
//!
//! This cfg(test)-only module executes the real private `evaluate` gate on a
//! bounded synthetic corpus of extrema pairs and records the observed gate
//! decision, error reason and reported ranges. It exposes no production API,
//! collects no evidence and never contacts a serving endpoint. Corpus rows are
//! generated by the stdlib-only Python oracle; this hook ignores the oracle's
//! `expected` field entirely so agreement cannot be forged by construction.
//!
//! Invocation (see docs/performance/CALIBRATION.md for the harness pattern):
//!   GRILL_POLICY_CALIBRATION_CORPUS=corpus.jsonl \
//!   GRILL_POLICY_CALIBRATION_RESULTS=results.jsonl \
//!     <test-binary> policy::policy_calibration::crosscheck_corpus --ignored --exact

use super::*;
use std::io::{BufRead, Read, Write};

// Corpus rows are bounded: at most this many bytes and rows, each carrying
// u64 numerator/denominator extrema and schema-bounded tolerances.
const CORPUS_CAP_BYTES: u64 = 128 * 1024 * 1024;
const CORPUS_CAP_ROWS: usize = 1_000_000;

fn extremum(row: &serde_json::Value, role: &str, bound: &str) -> Rational {
    let pair = &row[role][bound];
    let numerator = pair[0].as_u64().expect("extremum numerator must be u64");
    let denominator = pair[1].as_u64().expect("extremum denominator must be u64");
    assert!(denominator >= 1, "extremum denominator must be positive");
    Rational::from((numerator, denominator))
}

#[test]
#[ignore = "bounded offline calibration; requires explicit corpus and output paths"]
fn crosscheck_corpus() {
    let corpus = std::env::var_os("GRILL_POLICY_CALIBRATION_CORPUS")
        .expect("GRILL_POLICY_CALIBRATION_CORPUS");
    let output = std::env::var_os("GRILL_POLICY_CALIBRATION_RESULTS")
        .expect("GRILL_POLICY_CALIBRATION_RESULTS");
    let mut bytes = Vec::new();
    std::fs::File::open(corpus)
        .unwrap()
        .take(CORPUS_CAP_BYTES + 1)
        .read_to_end(&mut bytes)
        .unwrap();
    let corpus = bytes;
    assert!(
        u64::try_from(corpus.len()).unwrap() <= CORPUS_CAP_BYTES,
        "corpus exceeds the bounded input cap"
    );
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mut output = std::io::BufWriter::new(
        std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(output)
            .unwrap(),
    );
    let header = serde_json::json!({
        "kind":"policy-evaluate-crosscheck-v1",
        "corpus_sha256":evidence::digest(&corpus),
        "policy_sha256":evidence::digest(&std::fs::read(root.join("src/policy.rs")).unwrap()),
        "evaluator_sha256":evidence::binary_digest().unwrap()
    });
    serde_json::to_writer(&mut output, &header).unwrap();
    writeln!(output).unwrap();
    let mut rows = 0usize;
    for line in std::io::BufReader::new(corpus.as_slice()).lines() {
        rows += 1;
        assert!(
            rows <= CORPUS_CAP_ROWS,
            "corpus exceeds the bounded row cap"
        );
        let row: serde_json::Value = serde_json::from_str(&line.unwrap()).unwrap();
        let metric: Metric =
            serde_json::from_value(row["metric"].clone()).expect("unknown metric name");
        let max_regression_bps = row["max_regression_bps"]
            .as_u64()
            .and_then(|v| u32::try_from(v).ok())
            .expect("max_regression_bps must be u32");
        let max_reference_spread_bps = row["max_reference_spread_bps"]
            .as_u64()
            .and_then(|v| u32::try_from(v).ok())
            .expect("max_reference_spread_bps must be u32");
        assert!(
            max_regression_bps <= 9999 && max_reference_spread_bps <= 1_000_000,
            "tolerances outside admitted schema bounds"
        );
        let reference = [
            extremum(&row, "reference", "low"),
            extremum(&row, "reference", "high"),
        ];
        let candidate = [
            extremum(&row, "candidate", "low"),
            extremum(&row, "candidate", "high"),
        ];
        let coverage = || Coverage {
            expected_waves: 0,
            observed_waves: 0,
            eligible_waves: 0,
            expected_observations: 0,
            observed_observations: 0,
            expected_warmups: 0,
            eligible_warmups: 0,
        };
        let mut gate = Gate {
            cell: row["id"].as_str().unwrap().to_owned(),
            metric,
            sample_unit: None,
            max_regression_bps,
            max_reference_spread_bps,
            coverage: Roles {
                baseline: coverage(),
                candidate: coverage(),
                reference: coverage(),
            },
            ranges: Roles {
                baseline: None,
                candidate: Some(candidate),
                reference: Some(reference),
            },
            pooled_reference_range: None,
            adverse_bounds: None,
            decision: Outcome::Inconclusive,
            reason_codes: Vec::new(),
        };
        // decide() maps evaluate errors: arithmetic overflow is ERROR, every
        // other gate error is INCONCLUSIVE. The raw reason is recorded too.
        let evaluate_error = match evaluate(&mut gate, reference, candidate) {
            Ok(()) => None,
            Err(reason) => {
                gate.decision = if reason == Reason::ArithmeticOverflow {
                    Outcome::Error
                } else {
                    Outcome::Inconclusive
                };
                gate.reason_codes.push(reason);
                Some(reason.as_str())
            }
        };
        serde_json::to_writer(
            &mut output,
            &serde_json::json!({
                "id":row["id"],
                "report":{
                    "decision":gate.decision,
                    "evaluate_error":evaluate_error,
                    "reason_codes":gate.reason_codes,
                    "pooled_reference_range":gate.pooled_reference_range,
                    "adverse_bounds":gate.adverse_bounds,
                }
            }),
        )
        .unwrap();
        writeln!(output).unwrap();
    }
    output.flush().unwrap();
}
